project:
  type: website
  output-dir: docs
  resources:
    - resources/images
    - resources/icons
    - resources/files

website:
  title: "Edoardo Murgia - CV"
  site-url: "https://emunit.github.io/murgia-edoardo-cv"
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "About Me"
      - href: contents/formazione.qmd
        text: "Education"
      - href: contents/competenze.qmd
        text: "Skills"
      - href: contents/projects.qmd
        text: "Projects/Group-Works"

format:
  html:
    theme: cosmo
    toc: false